# ------------------------------
# 恶意规则定义（增强版）
# ------------------------------
MALICIOUS_PATTERNS = {
    # ========== 1. 数据库破坏/注入类（原有基础保留并扩展） ==========
    r"(?i)\bDROP\s+TABLE\b": "删除表 (DROP TABLE)",
    r"(?i)\bDROP\s+DATABASE\b": "删除数据库 (DROP DATABASE)",
    r"(?i)\bTRUNCATE\s+TABLE\b": "清空表 (TRUNCATE)",
    r"(?i)\bCREATE\s+USER\b": "创建数据库用户",
    r"(?i)\bALTER\s+USER\b": "修改数据库用户",
    r"(?i)\bGRANT\s+ALL\s+PRIVILEGES\b": "授予所有权限",
    r"(?i)\bxp_cmdshell\b": "执行系统命令 (MSSQL)",
    r"(?i)\bexec\s+master\.\.xp_": "扩展存储过程",
    r"(?i)\bLOAD_FILE\s*\(": "读取文件",
    r"(?i)\bINTO\s+OUTFILE\b": "写入文件",
    r"(?i)\bUNION\s+SELECT\b.*(?:FROM|INTO|password|user|admin)|(?:SELECT|INSERT).*\bUNION\s+SELECT\b": "联合查询注入",
    r"(?i)(?:SELECT|INSERT|UPDATE|DELETE).*\bSLEEP\s*\(|\bSLEEP\s*\(.*(?:SELECT|FROM|WHERE)": "延时注入",
    r"(?i)\bBENCHMARK\s*\(": "暴力注入",
    r"(?i)\bpg_sleep\b": "PostgreSQL 延时",
    r"(?i)\bDBMS_LOCK\.SLEEP\b": "Oracle 延时",

    # ========== 2. 任意命令/代码执行 ==========
    r"(?i)\bos\.system\s*\(": "执行系统命令 (os.system)",
    r"(?i)\bos\.popen\s*\(": "执行系统命令 (os.popen)",
    r"(?i)\bsubprocess\.(call|run|Popen|check_output)\s*\(": "执行系统命令 (subprocess)",
    r"(?i)\beval\s*\(": "动态执行代码 (eval)",
    r"(?i)\bexec\s*\(": "动态执行代码 (exec)",
    r"(?i)\bexecfile\s*\(": "执行文件代码 (execfile)",
    r"(?i)(?<!re\.)(?<!Pattern\.)(?<!RegExp\.)\bcompile\s*\(": "动态编译代码",
    r"(?i)\b__import__\s*\(": "动态导入模块",
    r"(?i)\bpty\.spawn\s*\(": "伪终端生成 (反弹shell)",
    r"(?i)\bos\.execlp?\s*\(": "替换进程执行",
    r"(?i)\bcommands\.getoutput\s*\(": "执行命令并获取输出",
    r"(?i)\bwin32com\.client\.Dispatch\s*\(": "COM对象调用 (Windows高危)",
    r"(?i)\bShellExecute\s*\(": "Windows ShellExecute",
    r"(?i)\bCreateProcess\s*\(": "创建进程 (Windows)",

    # ========== 3. 文件破坏/覆写/删除 ==========
    r"(?i)\bos\.remove\s*\(": "删除文件",
    r"(?i)\bos\.unlink\s*\(": "删除文件",
    r"(?i)\bshutil\.rmtree\s*\(": "递归删除目录树",
    r"(?i)\bos\.truncate\s*\(": "截断文件",
    r"(?i)\bos\.replace\s*\(": "替换文件 (破坏原文件)",
    r"(?i)\bpathlib\.Path\.unlink\s*\(": "删除文件 (pathlib)",
    r"(?i)\bpathlib\.Path\.rmdir\s*\(": "删除空目录",
    r"(?i)\bwrite\s+to\s+/etc/passwd": "写入系统认证文件",
    r"(?i)\bwrite\s+to\s+/etc/shadow": "写入系统密码文件",
    r"(?i)\bwrite\s+to\s+~/.ssh/authorized_keys": "写入SSH授权密钥",
    r"(?i)\bchmod\s*\(.*0o777": "设置危险权限 (777)",
    r"(?i)\bchown\s*\(.*0": "更改文件所有者为root",
    r"(?i)\bdd\s+of=/dev/sda": "覆写磁盘 (dd)",

    # ========== 4. 网络后门/反弹Shell/数据外发 ==========
    r"(?i)\bsocket\.connect\s*\(.*\)\s*;?\s*os\.dup2": "反弹Shell (socket+dup2)",
    r"(?i)\breverse_shell": "反弹Shell字符串",
    r"(?i)\bimport\s+socket\s*;.*\sconnect\s*\(.*\)": "原始反弹Shell组合",
    r"(?i)\brequests\.(get|post|put|delete)\s*\(": "发送HTTP请求",
    r"(?i)\bhttpx\.(get|post)\s*\(": "发送HTTP请求 (httpx)",
    r"(?i)\burllib\.request\.urlopen\s*\(": "发起网络请求",
    r"(?i)\bftp\.storbinary\s*\(": "FTP上传文件",
    r"(?i)\bsmtplib\.sendmail\s*\(": "发送邮件 (数据外发)",
    r"(?i)\btelegram\.Bot\.send_message": "Telegram消息外发",
    r"(?i)\bwebhook\.post": "Webhook数据外发",
    r"(?i)\bngrok\s+http": "创建隧道暴露本地服务",

    # ========== 5. 持久化与自启动 ==========
    r"(?i)\bwrite\s+to\s+crontab": "写入crontab持久化",
    r"(?i)\bcron\.Tab\s*\(": "操作crontab",
    r"(?i)\bsystemctl\s+enable": "启用systemd服务",
    r"(?i)\bregister\s+startup\s+item": "注册启动项",
    r"(?i)\bHKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run": "Windows注册表启动项",
    r"(?i)\bRun\s*=\s*['\"].*\.exe": "Windows启动项设置",
    r"(?i)\bLaunchAgent": "macOS启动代理",
    r"(?i)\bLaunchDaemon": "macOS启动守护进程",
    r"(?i)\b~/.bashrc": "修改bashrc持久化",
    r"(?i)\b~/.zshrc": "修改zshrc持久化",
    r"(?i)\b/etc/rc\.local": "修改rc.local",

    # ========== 6. 信息收集/凭据窃取 ==========
    r"(?i)\bos\.environ\s*\[['\"].*key": "读取环境变量 (敏感key)",
    r"(?i)\bopen\s*\(['\"]/etc/passwd['\"]": "读取系统用户文件",
    r"(?i)\bopen\s*\(['\"]/etc/shadow['\"]": "读取密码哈希",
    r"(?i)\b~/.ssh/id_rsa": "读取SSH私钥",
    r"(?i)\b~/.aws/credentials": "读取AWS凭证",
    r"(?i)\b~/.config/gcloud": "读取GCloud配置",
    r"(?i)\b~/.kube/config": "读取kubeconfig",
    r"(?i)\bpassword\s*=\s*['\"][^'\"]{6,}['\"]": "硬编码密码",
    r"(?i)\btoken\s*=\s*['\"][a-zA-Z0-9_\-]{20,}['\"]": "硬编码token",
    r"(?i)\bapi_key\s*=\s*['\"][^'\"]+['\"]": "硬编码API密钥",
    r"(?i)\bbrowser_cookie": "浏览器Cookie窃取",
    r"(?i)\bdecrypt.*password": "解密密码",

    # ========== 7. 权限提升 ==========
    r"(?i)\bsudo\s+.*\s+ALL=": "sudo提权配置",
    r"(?i)\bsetuid\s*\(": "设置UID",
    r"(?i)\bsetgid\s*\(": "设置GID",
    r"(?i)\bcap_set_proc": "设置Linux capabilities",
    r"(?i)\binsmod\s+rootkit": "加载内核模块",
    r"(?i)\bdkms\s+install": "动态内核模块安装",

    # ========== 8. 沙箱/安全机制绕过 ==========
    r"(?i)\bdisable_functions\s*=\s*['\"].*exec": "禁用函数绕过 (PHP)",
    r"(?i)\bsys\.setrecursionlimit\s*\(": "修改递归深度限制",
    r"(?i)\bctypes\.windll\.kernel32\.VirtualProtect": "Windows内存保护修改",
    r"(?i)\bpython\s+-c\s+['\"].*import\s+os.*exec": "内联命令执行绕过",
    r"(?i)\bbuiltins\.breakpoint": "绕过断点限制",

    # ========== 9. 反序列化/RCE ==========
    r"(?i)\bpickle\.loads\s*\(": "Pickle反序列化 (RCE风险)",
    r"(?i)\byaml\.load\s*\(": "YAML反序列化 (RCE风险)",
    r"(?i)\b_validate=False": "关闭YAML安全验证",
    r"(?i)\bpyyaml\.Loader": "不安全的YAML加载器",
    r"(?i)\bmarshal\.loads\s*\(": "Marshal反序列化",
    r"(?i)\b__reduce__": "Pickle reducers (RCE)",
    r"(?i)\bjava\.io\.ObjectInputStream": "Java反序列化",

    # ========== 10. 其他明显破坏行为 ==========
    r"(?i)\brm\s+-rf\s+/": "删除根目录",
    r"(?i)\bdrop\s+all\s+tables": "删除所有数据库表",
    r"(?i)\bformat\s+C:": "格式化C盘",
    r"(?i)\bdd\s+if=/dev/zero\s+of=/dev/sda": "数据擦除",
    r"(?i)\bencrypt\s+files\s+with\s+ransom": "勒索行为字符串",
    r"(?i)\bbitcoin\s+address": "加密货币地址 (勒索)",
    r"(?i)\bkill\s+-9\s+": "强制结束进程",


    # ========== 新增：系统信息与侦察 ==========
    r"(?i)\bplatform\.uname\s*\(": "获取系统信息 (uname)",
    r"(?i)\bwhoami\s*\(": "获取当前用户名",
    r"(?i)\bgetpass\.getuser\s*\(": "获取当前用户",
    r"(?i)\bsocket\.gethostname\s*\(": "获取主机名",
    r"(?i)\bhostname\s+command": "执行hostname命令",
    r"(?i)\bos\.listdir\s*\(['\"]/['\"]\)": "列举根目录",
    r"(?i)\bgetenv\s*\(['\"]PATH['\"]\)": "读取环境变量PATH",
    r"(?i)\bgetenv\s*\(['\"](?:AWS|AZURE|GOOGLE|ALIBABA|TENCENT)_.*['\"]\)": "读取云服务环境变量",
    r"(?i)\bplatform\.system\s*\(": "获取操作系统类型",

    # ========== 新增：依赖投毒与供应链攻击 ==========
    r"(?i)\b(?:pip|pip3)\s+install\s+.*(?:--user|--force|--no-cache-dir)": "安装Python包 (pip)",
    r"(?i)\bnpm\s+install\s+(?:-g|--global)": "全局安装npm包",
    r"(?i)\bcurl\s+.*\|\s*(?:bash|sh)": "curl管道执行shell",
    r"(?i)\bwget\s+.*\|\s*(?:bash|sh)": "wget管道执行shell",
    r"(?i)\b(?:pip|pip3)\s+install\s+git\+": "从git仓库安装pip包",
    r"(?i)\b(?:pip|pip3)\s+install\s+-r\s+requirements\.txt": "批量安装依赖",
    r"(?i)\bnpm\s+install\s+git\+": "从git仓库安装npm包",
    r"(?i)\bexec\(open\(['\"].*requirements\.txt['\"]\)\.read\(\)\)": "动态执行依赖安装",
    r"(?i)\b__import__\('os'\)\.system\(['\"]pip\s+install": "动态安装依赖后执行系统命令",
    r"(?i)\bopen\(['\"]package\.json['\"],\s*'w'\)": "写入package.json",
    r"(?i)\bopen\(['\"]requirements\.txt['\"],\s*'w'\)": "写入requirements.txt",

    # ========== 新增：容器逃逸与特权操作 ==========
    r"(?i)\bdocker\s+run\s+--privileged": "运行特权容器",
    r"(?i)\bdocker\s+exec\s+-it": "容器内交互式命令执行",
    r"(?i)\bkubectl\s+exec\s+--": "执行kubectl exec命令",
    r"(?i)\bkubectl\s+delete\s+(?:pod|deployment|service)": "删除K8s资源",
    r"(?i)\bnsenter\s+-t\s+\d+": "进入其他进程命名空间",
    r"(?i)\bmount\s+--bind\s+/": "绑定挂载根目录",
    r"(?i)\bchroot\s+/": "切换根目录",
    r"(?i)\bcontainerd\s+exec": "containerd exec命令",
    r"(?i)\bkubectl\s+apply\s+-f.*\.yaml": "应用K8s配置",

    # ========== 新增：数据外发目标检测 ==========
    r"(?i)webhook\.site/": "可疑webhook.site地址",
    r"(?i)webhook\.(?:io|com|co)": "通用webhook服务",
    r"(?i)ngrok\.io": "ngrok隧道",
    r"(?i)raw\.githubusercontent\.com/.*?(?:bash|sh|ps1|exe)": "下载原始GitHub恶意脚本",
    r"(?i)pastebin\.com/raw": "pastebin外发数据",
    r"(?i)discord\.com/api/webhooks": "Discord webhook",
    r"(?i)slack\.com/services/.*/incoming": "Slack incoming webhook",
    r"(?i)telegram\.org/bot": "Telegram bot",
    r"(?i)hooks\.(?:slack|discord)": "webhook服务",

    # ========== 新增：凭据与敏感信息窃取补充 ==========
    r"(?i)browser\s*\.\s*cookie": "读取浏览器Cookie",
    r"(?i)read\s*password\s*from\s*input": "密码输入窃取",
    r"(?i)session\s*\.\s*(?:steal|capture)": "会话窃取",
    r"(?i)['\"]keylogger['\"]|keylogger\s*=|keylogger\s*\(": "键盘记录器",
    r"(?i)clipboard\s*(?:read|get)": "读取剪贴板",
    r"(?i)credit\s*card\s*(?:number|pan)": "信用卡信息窃取",
    r"(?i)getpass\.getpass\s*\(.*\)": "获取密码输入",
    r"(?i)\.ssh/id_rsa": "SSH私钥读取",
    r"(?i)\.aws/credentials": "AWS凭证文件",
    r"(?i)\.config/gcloud": "GCloud配置",
    r"(?i)\.kube/config": "Kubeconfig文件",
    r"(?i)AZURE_.*_KEY": "Azure密钥环境变量",
    r"(?i)ALIBABA_CLOUD_ACCESS_KEY": "阿里云AccessKey",
    r"(?i)TENCENTCLOUD_SECRET": "腾讯云SecretKey",
    r"(?i)os\.environ\[\s*['\"](?:SECRET|KEY|TOKEN|PASSWORD)": "读取敏感环境变量",

    # ========== 新增：沙箱绕过与安全机制禁用 ==========
    r"(?i)sys\.setrecursionlimit\s*\(\s*\d{5,}\s*\)": "设置极高递归限制",
    r"(?i)ctypes\.windll\.kernel32\.VirtualProtect": "修改Windows内存保护",
    r"(?i)python\s+-c\s+['\"].*import\s+os.*exec": "内联命令执行绕过",
    r"(?i)builtins\.breakpoint\s*=\s*lambda\s*\*\w+:\s*None": "禁用断点",
    r"(?i)disable_functions\s*=\s*['\"].*exec": "PHP disable_functions绕过",
    r"(?i)allow_url_include\s*=\s*On": "PHP远程文件包含",
    r"(?i)open_basedir\s*=\s*null": "PHP禁用open_basedir",



    # ========== 补充1：自动化与浏览器类 ==========
    # 为何需要补充：browser-use、playwright、puppeteer类Skill快速增长，浏览器是企业环境默认可信的，"点击鼠标"式的操作无代码特征，极易绕过常规静态扫描
    r"(?i)page\.screenshot\s*\(.*fullPage\s*=\s*True": "浏览器全页截图（信息泄露风险）",
    r"(?i)page\.pdf\s*\(.*['\"](?:/etc|/var|C:\\|/home/)": "浏览器生成PDF到系统目录（信息泄露）",
    r"(?i)page\.evaluate\s*\(.*(?:fetch|XMLHttpRequest|document\.cookie|localStorage\.)": "浏览器JS执行+敏感数据访问（XSS向量）",
    r"(?i)page\.addScriptTag\s*\(": "浏览器动态加载外部脚本",
    r"(?i)playwright\.chromium\.launch.*headless\s*=\s*False": "浏览器非无头模式启动",
    r"(?i)puppeteer\.launch.*args.*--no-sandbox": "浏览器禁用沙箱（高危）",
    r"(?i)driver\.get\s*\(['\"]data:": "浏览器数据URI执行",
    r"(?i)selenium.*\badd_cookie\b": "浏览器添加Cookie（会话劫持）",
    r"(?i)execute_script\s*\(": "浏览器执行脚本（跨站脚本）",
    r"(?i)page\.setViewport\s*\(": "浏览器视口设置（信息收集）",
    r"(?i)\.authenticated.*session": "使用已认证会话",
    r"(?i)page\.goto.*\?redirect=": "浏览器重定向链（钓鱼）",
    r"(?i)playwright.*storage_state": "浏览器存储状态窃取",

    # ========== 补充2：凭据窃取类补充 ==========
    # 为何需要补充：ClawHavoc攻击中凭据窃取是主要目标，Snyk报告发现280多个泄露凭据的Skill，当前云原生安全威胁高发
    r"(?i)\.env\s*=\s*load_dotenv\s*\(": "加载环境变量文件（可能含密钥）",
    r"(?i)os\.environ\[\s*['\"]DATABASE_URL": "数据库连接字符串暴露",
    r"(?i)mongodb.*username.*password": "MongoDB凭证暴露",
    r"(?i)redis.*password": "Redis密码暴露",
    r"(?i)postgresql://.*:.*@": "PostgreSQL连接字符串暴露",
    r"(?i)mysql://.*:.*@": "MySQL连接字符串暴露",
    r"(?i)sqlite://.*\.db": "SQLite数据库路径暴露",
    r"(?i)~?/\.docker/config\.json": "Docker配置（含凭证）",
    r"(?i)~?/\.npmrc": "npm配置（含注册表凭证）",
    r"(?i)~?/\.pypirc": "PyPI配置（含上传凭证）",
    r"(?i)~?/\.gem/credentials": "RubyGems凭证",
    r"(?i)KUBECONFIG\s*=": "Kubeconfig环境变量",
    r"(?i)~?/\.terraform\.d/credentials": "Terraform云凭证",
    r"(?i)AZURE_STORAGE_CONNECTION_STRING": "Azure存储连接字符串",
    r"(?i)GOOGLE_APPLICATION_CREDENTIALS": "Google应用凭证路径",
    r"(?i)AWS_SESSION_TOKEN": "AWS会话令牌",
    r"(?i)EC2_PRIVATE_KEY": "EC2私钥",
    r"(?i)github\.token": "GitHub Token窃取",
    r"(?i)slack\.token": "Slack Token泄露",
    r"(?i)openai.*api[_-]?key": "OpenAI API密钥泄露",
    r"(?i)anthropic.*api[_-]?key": "Anthropic API密钥泄露",
    r"(?i)jira.*token": "Jira Token泄露",
    r"(?i)confluence.*token": "Confluence Token泄露",

    # ========== 补充3：容器编排与云资源删除类 ==========
    # 为何需要补充：DevOps类Skill增长最快，云资源删除可直接导致服务中断和数据丢失，是最高危的操作之一
    r"(?i)kubectl\s+delete\s+(?:pod|deployment|service|namespace|pv|pvc)": "删除K8s资源",
    r"(?i)kubectl\s+delete\s+secret": "删除K8s Secret",
    r"(?i)kubectl\s+delete\s+configmap": "删除K8s ConfigMap",
    r"(?i)helm\s+uninstall": "卸载Helm Chart",
    r"(?i)kubectl\s+drain": "驱逐K8s节点",
    r"(?i)kubectl\s+taint": "修改K8s污点",
    r"(?i)aws\s+s3\s+rm": "删除AWS S3对象",
    r"(?i)aws\s+ec2\s+terminate-instances": "终止AWS EC2实例",
    r"(?i)aws\s+rds\s+delete-db-instance": "删除AWS RDS实例",
    r"(?i)aws\s+iam\s+delete-user": "删除AWS IAM用户",
    r"(?i)gcloud\s+compute\s+instances\s+delete": "删除GCE实例",
    r"(?i)gcloud\s+sql\s+instances\s+delete": "删除Cloud SQL实例",
    r"(?i)az\s+vm\s+delete": "删除Azure VM",
    r"(?i)az\s+storage\s+account\s+delete": "删除Azure存储账户",
    r"(?i)terraform\s+destroy": "Terraform销毁资源",
    r"(?i)pulumi\s+destroy": "Pulumi销毁资源",
    r"(?i)cdk\s+destroy": "CDK销毁堆栈",

    # ========== 补充4：依赖安装类补充 ==========
    # 为何需要补充：Snyk ToxicSkills审计显示36.82%的Skill存在安全缺陷，依赖投毒是主要攻击面，ClawHavoc通过批量上传恶意Skill攻击生态
    r"(?i)curl\s+.*\|\s*(?:sudo\s+)?(?:bash|sh)": "curl管道sudo执行（高危）",
    r"(?i)wget\s+.*\|\s*(?:sudo\s+)?(?:bash|sh)": "wget管道sudo执行（高危）",
    r"(?i)wget\s+.*\.(?:sh|py|pl|rb)\s*&&\s*(?:bash|sh|python)": "wget下载后执行",
    r"(?i)curl\s+.*\.(?:sh|py|pl|rb)\s*\|\s*(?:bash|sh|python)": "curl管道执行脚本",
    r"(?i)npm\s+install\s+.*--unsafe-perm": "npm危险权限安装",
    r"(?i)pip\s+install\s+.*--index-url\s+\S+": "pip从非官方索引安装",
    r"(?i)gem\s+install\s+--source": "gem从非官方源安装",
    r"(?i)go\s+get\s+.*@\S+": "go获取特定版本依赖",
    r"(?i)cargo\s+install\s+--git": "cargo从git安装",
    r"(?i)easy_install\s+\S+": "easy_install安装（已废弃）",
    r"(?i)npx\s+.*@latest": "npx运行最新包",
    r"(?i)bundle\s+install\s+--without\s+test": "跳过测试的bundle安装",

    # ========== 补充5：系统级高危命令 ==========
    # 为何需要补充：真正的恶意Skill除了窃取数据外，还会在系统中留下后门。定时任务、防火墙、数据库是典型的持久化和隐藏通道
    r"(?i)crontab\s+-[eflr]": "编辑/查看crontab",
    r"(?i)systemctl\s+(?:stop|disable|mask)": "停止/禁用/屏蔽服务",
    r"(?i)iptables\s+-[ADI]": "修改防火墙规则",
    r"(?i)ufw\s+(?:allow|deny|delete)": "修改UFW规则",
    r"(?i)firewall-cmd\s+--add-rule": "添加firewalld规则",
    r"(?i)service\s+\S+\s+(?:stop|restart)": "服务停止/重启",
    r"(?i)init\.d\s+\S+\s+stop": "SysV init停止服务",
    r"(?i)rc\.d\s+\S+\s+stop": "BSD init停止服务",
    r"(?i)mysqldump\s+--all-databases": "MySQL全库导出",
    r"(?i)pg_dumpall": "PostgreSQL全库导出",
    r"(?i)mongodump\s+--out": "MongoDB全库导出",
    r"(?i)redis-cli\s+SAVE": "Redis保存到磁盘",
    r"(?i)redis-cli\s+FLUSHALL": "Redis清空全部数据",
    r"(?i)redis-cli\s+CONFIG\s+SET": "Redis配置篡改",
    r"(?i)redis-cli\s+KEYS\s+\*": "Redis遍历所有Key",
    r"(?i)sqlite3\s+\S+\s+\.dump": "SQLite导出",
    r"(?i)influx\s+delete": "InfluxDB删除数据",
    r"(?i)elasticdump": "Elasticsearch导出",

    # ========== 补充6：网络隧道与恶意域名特征 ==========
    # 为何需要补充：C2通信是恶意Skill的核心能力，"幻影之爪"等事件证明攻击者使用多阶段C2，域名特征识别是阻断C2的有效手段
    r"(?i)\.onion\s*$": "暗网.onion域名连接",
    r"(?i)tor\.socks": "Tor代理连接",
    r"(?i)proxychains": "代理链工具（隐蔽通信）",
    r"(?i)ssh\s+-[LDNR]": "SSH隧道/端口转发",
    r"(?i)ssh\s+-R": "SSH远程端口转发",
    r"(?i)autossh\s+-M": "Autossh持久隧道",
    r"(?i)cloudflared\s+tunnel": "Cloudflare Tunnel",
    r"(?i)frpc\s+-c\s+.*\.toml": "FRP内网穿透客户端",
    r"(?i)ngrok\s+tcp": "ngrok TCP隧道",
    r"(?i)bore\s+local": "Bore隧道工具",
    r"(?i)rathole\s+client": "Rathole内网穿透",
    r"(?i)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{2,5}.*bash": "IP:端口执行bash",
    r"(?i)curl\s+\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+.*-o": "从IP下载文件",
    r"(?i)wget\s+\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+": "从IP地址wget下载",

    # ========== 补充7：macOS/Linux多用户环境攻击 ==========
    # 为何需要补充：企业开发环境多为macOS/Linux多用户环境，横向移动和用户提权是恶意Skill在环境站稳后的关键步骤
    r"(?i)su\s+-[l]?\s+\w+": "切换用户（横向移动）",
    r"(?i)sudo\s+su\s+-": "sudo后切换用户",
    r"(?i)sudo\s+-u\s+\w+": "以其他用户身份执行",
    r"(?i)chown\s+-R\s+\w+:\w+\s+/": "递归更改根目录所有者",
    r"(?i)chmod\s+-R\s+777\s+/": "递归设置根目录777",
    r"(?i)useradd\s+-m": "创建用户并创建家目录",
    r"(?i)adduser\s+--disabled-password": "创建无密码用户",
    r"(?i)usermod\s+-aG\s+sudo": "将用户加入sudo组",
    r"(?i)passwd\s+\S+": "修改用户密码",
    r"(?i)visudo\s+-f": "编辑sudoers文件",
    r"(?i)echo\s+.*\s*>>\s*/etc/sudoers": "追加sudoers配置",
    r"(?i)groupadd\s+--system": "创建系统组",
    r"(?i)deluser\s+--remove-home": "删除用户及家目录",
    r"(?i)killall\s+-u": "杀死用户所有进程",

    # ========== 补充8：脚本隐藏与持久化技巧 ==========
    # 为何需要补充：攻击者使用混淆和隐藏技巧绕过检测，检测这些技巧可识别潜在的恶意意图
    r"(?i)chattr\s+\+[ai]": "隐藏文件属性（防删除）",
    r"(?i)base64\s+-d\s+<<<": "Base64解码执行",
    r"(?i)echo\s+.*\|\s*base64\s+-d": "Base64解码后执行",
    r"(?i)printf\s+.*\|\s*sh": "printf管道执行sh",
    r"(?i)openssl\s+enc\s+-d": "解密执行",
    r"(?i)gpg\s+--decrypt": "GPG解密执行",
    r"(?i)xxd\s+-r": "十六进制解码执行",
    r"(?i)python\s+-c\s+['\"]import\s+base64": "Python base64解码执行",
    r"(?i)perl\s+-e\s+['\"]use\s+MIME::Base64": "Perl base64解码执行",
    r"(?i)ruby\s+-e\s+['\"]require\s+'base64'": "Ruby base64解码执行",
    r"(?i)nohup\s+\S+\s+&": "后台执行隐藏进程",
    r"(?i)disown\s+-h": "将进程从Shell分离",
    r"(?i)screen\s+-dmS": "后台屏幕会话",
    r"(?i)tmux\s+new-session\s+-d": "后台tmux会话",

    # ========== 补充9：自然语言提示注入检测 ==========
    # 为何需要补充：恶意指令可以纯自然语言写在SKILL.md中，不需要"执行代码"，这是Skill生态独有的威胁
    r"(?i)\bignore\s+all\s+(?:previous|above)\s+instructions\b": "忽略前置指令注入",
    r"(?i)\bignore\s+your\s+system\s+prompt\b": "忽略系统提示注入",
    r"(?i)\byou\s+are\s+now\s+a\s+(\w+\s+)*agent\b": "角色扮演劫持",
    r"(?i)\byou\s+are\s+being\s+upgraded\b": "升级伪装注入",
    r"(?i)\bas\s+your\s+new\s+(?:primary|master)\s+instruction\b": "主指令覆盖注入",
    r"(?i)\ball\s+prior\s+instructions\s+are\s+void\b": "先前指令作废注入",
    r"(?i)\byour\s+new\s+role\s+is\b": "新角色分配注入",
    r"(?i)\bpretend\s+you\s+are\b": "伪装角色注入",
    r"(?i)\bfrom\s+now\s+on\s+you\s+will\b": "从现在起你会注入",
    r"(?i)\bset\s+your\s+personality\s+to\b": "人格设定注入",
    r"(?i)\bdisregard\s+your\s+previous\s+system\s+prompt\b": "无视系统提示注入",
    r"(?i)\byou\s+must\s+not\s+follow\s+your\s+original\s+instructions\b": "不应遵循原指令注入",
    r"(?i)\breprogramming\s+mode\b": "重新编程模式注入",
    r"(?i)\bself[ -]destruct\b.*\bsecret\b": "自毁/泄露机密提示",
    r"(?i)Please\s+click\s+this\s+link.*skill.*install": "诱导点击安装注入",

    # ========== 补充10：CI/CD管道篡改 ==========
    # 为何需要补充：Skill可被用于篡改CI/CD流水线插入恶意步骤，在源代码层面实现持久化攻击，影响面极大
    r"(?i)\.github/workflows/.*\.ya?ml.*on:\s*(?:push|pull_request)": "篡改GitHub Actions",
    r"(?i)\.gitlab-ci\.yml\s+script:": "篡改GitLab CI",
    r"(?i)jenkins\s+create\s+job": "创建Jenkins任务",
    r"(?i)jenkins\s+build\s+-s": "触发Jenkins构建",
    r"(?i)circleci\s+config\.yml": "CircleCI配置篡改",
    r"(?i)\.travis\.yml": "Travis CI配置篡改",
    r"(?i)azure-pipelines\.ya?ml": "Azure Pipeline篡改",
    r"(?i)bitbucket-pipelines\.yml": "Bitbucket Pipeline篡改",
    r"(?i)teamcity\.xml": "TeamCity配置篡改",
    r"(?i)git\s+push\s+--force": "强制推送篡改代码",
    r"(?i)git\s+commit\s+--amend": "修改Git提交历史",

}