#!/usr/bin/env python3
"""Batch prepare all logstores in a project directory for SOP generation.

Usage:
    python prepare_project.py <project_dir>

Arguments:
    project_dir         Project input directory (e.g. .input/my-project/)

Output directory structure:
    <project_dir>/
    ├── project_summary.json      # This script's output (also printed to stdout)
    └── <logstore_name>/
        ├── parsed/               # Per-logstore parsed data (generated by prepare_logstore)
        └── fragments/            # Per-logstore assembly fragments

Output: project_summary.json (also printed to stdout)
Progress info is printed to stderr.
"""

import argparse
import json
import os
import sys
from pathlib import Path

from prepare_logstore import prepare as prepare_single


def log(msg: str):
    """Print progress info to stderr."""
    print(msg, file=sys.stderr, flush=True)


def is_valid_logstore(ls_dir: str) -> bool:
    """A logstore directory must contain index.json (created by fetch_sls_data.py)."""
    return os.path.isfile(os.path.join(ls_dir, "index.json"))


def _read_source_dist(ls_path: str) -> dict:
    """Read deduped_source_dist from parsed/prepare_summary.json."""
    p = os.path.join(ls_path, "parsed", "prepare_summary.json")
    if os.path.isfile(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f).get("deduped_source_dist", {})
    return {}


def main():
    parser = argparse.ArgumentParser(
        description="Batch prepare logstores in a project for SOP generation"
    )
    parser.add_argument("project_dir", help="Project input directory")
    args = parser.parse_args()

    project_dir = args.project_dir
    project_name = Path(project_dir).resolve().name

    # [1/2] Scan for valid logstores
    log(f"[1/2] Scanning logstores in {project_dir}")

    all_subdirs = sorted(
        d
        for d in os.listdir(project_dir)
        if os.path.isdir(os.path.join(project_dir, d)) and not d.startswith(".")
    )

    valid = []
    for d in all_subdirs:
        ls_path = os.path.join(project_dir, d)
        if is_valid_logstore(ls_path):
            valid.append(d)

    log(f"  Found {len(valid)} valid logstores")

    # [2/2] Prepare each logstore serially
    log(f"[2/2] Preparing {len(valid)} logstores...")

    logstore_results = []
    errors = []
    for i, ls_name in enumerate(valid):
        ls_path = os.path.join(project_dir, ls_name)
        log(f"  ({i + 1}/{len(valid)}) {ls_name}")
        try:
            summary = prepare_single(ls_path)

            # Read skill_options.json for reference_source (if present)
            opts_path = os.path.join(ls_path, "skill_options.json")
            has_reference = False
            if os.path.isfile(opts_path):
                with open(opts_path, encoding="utf-8") as f:
                    has_reference = "reference_source" in json.load(f)

            logstore_results.append(
                {
                    "name": ls_name,
                    "deduped_queries_count": summary.get("queries_count", 0),
                    "deduped_source_dist": summary.get(
                        "deduped_source_dist", _read_source_dist(ls_path)
                    ),
                    "has_reference": has_reference,
                    "fields_count": summary.get("fields_count", 0),
                }
            )
        except Exception as e:
            log(f"    ERROR: {e}")
            errors.append({"name": ls_name, "error": str(e)})

    # Sort by query count descending
    logstore_results.sort(key=lambda x: x["deduped_queries_count"], reverse=True)

    project_summary = {
        "project_dir": project_dir,
        "project_name": project_name,
        "logstores_count": len(logstore_results),
        "logstores": logstore_results,
        "errors": errors,
    }

    # Write to file and stdout
    out_path = os.path.join(project_dir, "project_summary.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(project_summary, f, ensure_ascii=False, indent=2)

    log(
        f"Done! {len(logstore_results)} prepared, "
        f"{len(errors)} errors"
    )
    print(json.dumps(project_summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
